version: "3.8"

services:
  app1:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ecommerce
      - DB_PORT=3306
    depends_on:
      - mysql 
    networks:
      - app-net

  app2:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ecommerce
      - DB_PORT=3306
    depends_on:
      - mysql 
    networks:
      - app-net

  app3:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ecommerce
      - DB_PORT=3306
    depends_on:
      - mysql 
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app-net
      
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
